name: Trivy Image Scan
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        run: |
          docker build -t my-first-image:latest .
      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@v0.24.0
        with:
          image-ref: "my-first-image:latest"
          format: "table"
          exit-code: "1"
          severity: "HIGH,CRITICAL"
